version: '3.8'

services:
  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    environment:
      - DATABASE_URL=postgresql://auth_user:secure_password@db/auth_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

  data_service:
    build:
      context: ./data_service
    container_name: data_service
    environment:
      - DATABASE_URL=postgresql://auth_user:secure_password@db/auth_service
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=auth_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
